Sys.setlocale("LC_TIME", "English")
fileUrl <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(fileUrl, destfile = "./exdata_data_household_power_consumption.zip", method = "curl")
unzip("./exdata_data_household_power_consumption.zip", exdir = ".")
hpc <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?",nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='')
hpc$Date <- as.Date(hpc$Date, format="%d/%m/%Y")
hpc2 <- subset(hpc, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(hpc)
datetime <- paste(as.Date(hpc2$Date), hpc2$Time)
hpc2$Datetime <- as.POSIXct(datetime)
plot(hpc2$Datetime,hpc2$Global_active_power, type="l",ylab="Global Active Power (kilowatts)", xlab="")
dev.copy(png, file="plot2.png", height=480, width=480)
dev.off()
