## file household_power_consumption.txt must be in your working directory 
Sys.setlocale("LC_TIME", "English")
hpc <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?",nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='')
hpc$Date <- as.Date(hpc$Date, format="%d/%m/%Y")
hpc2 <- subset(hpc, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(hpc)
datetime <- paste(as.Date(hpc2$Date), hpc2$Time)
hpc2$Datetime <- as.POSIXct(datetime)
par(mfrow=c(2,2), mar=c(4,4,1,1), oma=c(0,0,2,0))
with(hpc2, {
plot(Global_active_power~Datetime, type="l",ylab="Global Active Power", xlab="")
plot(Voltage~Datetime, type="l",ylab="Voltage", xlab="datetime")
plot(Sub_metering_1~Datetime, type="l",ylab="Energy sub metering", xlab="")
lines(Sub_metering_2~Datetime,col='Red')
lines(Sub_metering_3~Datetime,col='Blue')
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, bty="n",legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(Global_reactive_power~Datetime, type="l",ylab="Global_reactive_power",xlab="datetime")})
dev.copy(png, file="plot4.png", height=480, width=480)
dev.off()
