Sys.setlocale("LC_TIME", "English")
fileUrl <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(fileUrl, destfile = "./exdata_data_household_power_consumption.zip", method = "curl")
unzip("./exdata_data_household_power_consumption.zip", exdir = ".")
hpc <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?",nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
hpc$Date <- as.Date(hpc$Date, format="%d/%m/%Y")
hpc2 <- subset(hpc, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
datetime <- paste(as.Date(hpc2$Date), hpc2$Time)
hpc2$Datetime <- as.POSIXct(datetime)
with(hpc2,{plot(hpc2$Datetime,hpc2$Sub_metering_1, type="l",ylab="Energy sub metering", xlab="")
lines(hpc2$Datetime,hpc2$Sub_metering_2,col='Red')
lines(hpc2$Datetime,hpc2$Sub_metering_3, col='Blue')})
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2,legend=c("sub metering 1", "sub metering 2", "sub metering 3"))
dev.copy(png, file="plot3.png", height=480, width=480)
dev.off()

